# Generated by Django 5.0 on 2023-12-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_active_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
